# Description: cls
licenses(["notice"])

package(
    default_visibility = ["//visibility:public"],
)

exports_files([
    "cls_log_sink_test.yaml",
])

cc_library(
    name = "mock_post_log_response",
    hdrs = ["mock_post_log_response.h"],
)
